trigger:
  branches:
    include:
      - main   # adjust your branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '18.x'

stages:
  - stage: Test
    displayName: Run Playwright Tests
    jobs:
      - job: Playwright
        displayName: Playwright Tests
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: "Install Node.js"

          - script: |
              npm ci
            displayName: "Install dependencies"

          - script: |
              npx playwright install --with-deps
            displayName: "Install Playwright browsers"

          - script: |
              npx playwright test --project=chromium 090Product.spec.ts
            displayName: "Run Playwright tests"


